spring:
  application:
    name: hibernate-flyway-example

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db.migration